### ISSUE TITLE
The Incanter example doesn't work with clojure-1.8.0

### ISSUE THREAD

**Issue by abo-abo** [clj-commons/pomegranate#94] opened 2018-01-01 22:05 UTC
I'm running this code snippet:

```clojure
(use '[cemerick.pomegranate :only (add-dependencies)])
(add-dependencies :coordinates '[[incanter "1.5.7"]]
                  :repositories (merge cemerick.pomegranate.aether/maven-central
                                       {"clojars" "https://clojars.org/repo"}))
(require '(incanter core stats charts))
```

It doesn't work either with clojure-1.8.0 or with clojure-1.7.0. It does work with clojure-1.6.0.

**Comment by abo-abo** [comment] 2018-01-01 23:03
OK, after some digging I got `add-dependencies` to work with:

```clojure
:dependencies [[org.clojure/clojure "1.9.0"]
               [org.tcrawley/dynapath "0.2.5"]
               [com.cemerick/pomegranate "0.4.0"]]
```

I can understand if dynapath wanted to remove some code for Java 9, it may still be useful after that; but it looks like pomegranate 1.0.0 doesn't do what it says on the tin anymore.

**Comment by agodde** [comment] 2018-01-25 10:00
Can confirm the issue and the provided solution by @abo-abo.
However, I would prefer version 1.0.0 would just work by itself ;)

**Comment by mikub** [comment] 2018-03-31 11:44
can confirm that this does not work on clojure 1.7.0 either:
```clojure
(let [new-cl (-> (Thread/currentThread)
               (.getContextClassLoader)
               (clojure.lang.DynamicClassLoader.))]
(cemerick.pomegranate/add-dependencies :coordinates [['com.draines/postal "2.0.2"]]
                                      :classloader new-cl)
(.setContextClassLoader (Thread/currentThread) new-cl)
(require 'postal.core))
FileNotFoundException Could not locate postal/core__init.class or postal/core.clj on classpath.  clojure.lang.RT.load (RT.java:449)
```
Examinig the classloader *shows* the postal's jar on the classpath though...
I tried this in REPL and uberjar and neither works. Also tried to inject dependencies directly into @clojure.lang.Compiler/LOADER, but no joy either. `*use-context-classloader*` is set to true.

Since I need the pomegrenate 1.0.0 because of its features it would be great to hear form @cemerick  at least in terms of what set up should 1.0.0 work with (i.e. clojure / java versions the 1.0.0 release was tested with). I guess there are some shenanigans in terms of how RT handles classloaders (plus repl vs no repl etc.)...

**Comment by razum2um** [comment] 2018-07-13 10:52
@abo-abo @agodde please, take a look on PR above and try if it's working now in your setup

**Comment by lread** [comment] 2023-01-17 17:08
This is a pretty old issue, but after I update dynapath to the current release, I'll see if I can still reproduce the issue.

**Comment by lread** [comment] 2023-01-17 21:49
Unfortunately, nobody elaborated beyond "it doesn't work" which leaves me wondering what failure symptom to expect.

Note that since this issue was raised the example in the README was updated to reference incanter v1.9.2. 

I can run the incanter README example in clojure versions 1.11, 1.10, 1.9, 1.8, 1.7. 
I do get a failure in Clojure 1.6.
```Clojure
user=> (require '(incanter core stats charts))
CompilerException java.io.FileNotFoundException: Could not locate clojure/core/matrix__init.class or clojure/core/matrix.clj on classpath: , compiling:(incanter/internal.clj:1:1) 
```

Gonna close this one for now. If someone provides an example detailing an unexpected failure, I am happy to have a peek.

**Closed by lread** 2023-01-17 21:49 UTC
Labels: insufficient-info
