### ISSUE TITLE
Import loaded class

### ISSUE THREAD

**Issue by kostafey** [clj-commons/pomegranate#97] opened 2018-01-14 22:30 UTC
How can I import classes from added jars?
This fails with error:
```
(cemerick.pomegranate/add-classpath "~/.m2/repository/com/my/myjar.jar")
(import 'com.my.Klass)
```
```
1. Unhandled java.lang.ClassNotFoundException
    com.my.Klass

       URLClassLoader.java:  381  java.net.URLClassLoader/findClass
   DynamicClassLoader.java:   69  clojure.lang.DynamicClassLoader/findClass
          ClassLoader.java:  424  java.lang.ClassLoader/loadClass
   DynamicClassLoader.java:   77  clojure.lang.DynamicClassLoader/loadClass
          ClassLoader.java:  357  java.lang.ClassLoader/loadClass
                Class.java:   -2  java.lang.Class/forName0

```
Dynamic classloader with `"~/.m2/repository/com/my/myjar.jar"` still presents in the REPL for few minutes then disappears. But I can't import my classes from this jar.

**Comment by lread** [comment] 2023-01-17 17:05
@kostafey it has been a long time since you raised this, but I'll see if I can reproduce the issue sometime soon and follow up.

**Comment by lread** [comment] 2023-01-18 00:09
Ok, I'll test with an arbitrary library with classes, why not... apach commons lang...

## Sanity Test
Let's start with a sanity test by explicitly bringing in the dep the normal way:

```Clojure
❯ clj -Sdeps '{:deps {org.apache.commons/commons-lang3 {:mvn/version "3.12.0"}}}'
Clojure 1.11.1
user=> (import 'org.apache.commons.lang3.StringUtils)
org.apache.commons.lang3.StringUtils
user=> (StringUtils/substringBetween "one two three two" "two")
" three "
```

That looks good.

## With pomegranate
Now let's try to bring in that dep with pomegranate, I'll do so the same way you did.
The jar will will have been downloaded by the above sanity test, so we do not have to worry about that.

```Clojure
❯ clj -Sdeps '{:deps {clj-commons/pomegranate {:mvn/version "1.2.1"}}}'               
Clojure 1.11.1
user=> (require '[cemerick.pomegranate :as pom])
nil
user=> (pom/add-classpath "~/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar")
nil
user=> (import 'org.apache.commons.lang3.StringUtils)
org.apache.commons.lang3.StringUtils
user=> (StringUtils/substringBetween "one two three two" "two")
" three "
```

This seems good as well. Maybe something was fixed since you raised this issue.

I'll close it up with a "cannot-reproduce" status. Feel free to comment/reopen, dear reader, if you cannot get this working.

**Closed by lread** 2023-01-18 00:09 UTC
Labels: cannot-reproduce
